### ISSUE TITLE
 "antechamber" failed

### ISSUE THREAD

**Issue by musabbirsaeed** [Acellera/parameterize#3]
2020-02-19 10:53:12,649 - parameterize.parameterization.cli - INFO - Method: AM1-BCC
Traceback (most recent call last):
  File "/home/saeed/miniconda3/envs/htmd1.21.0/bin/parameterize", line 11, in <module>
    sys.exit(main_parameterize())
  File "/home/saeed/miniconda3/envs/htmd1.21.0/lib/python3.6/site-packages/parameterize/parameterization/cli.py", line 890, in main_parameterize
    mol = _fit_charges(mol, args, qm_calculator, initial_mol.atomtype)
  File "/home/saeed/miniconda3/envs/htmd1.21.0/lib/python3.6/site-packages/parameterize/parameterization/cli.py", line 619, in _fit_charges
    mol = fitChargesWithAntechamber(mol, type="bcc", molCharge=args.charge)
  File "/home/saeed/miniconda3/envs/htmd1.21.0/lib/python3.6/site-packages/parameterize/charge/charge.py", line 170, in fitChargesWithAntechamber
    raise RuntimeError('"antechamber" failed')
RuntimeError: "antechamber" failed

Antechamber is keep failing.  
Please help me out to solve the problem.

**Comment by stefdoerr** [comment]
Hey, can you check if there is `antechamber` file in `/home/saeed/miniconda3/envs/htmd1.21.0/bin/`

**Comment by MASaeed44** [comment]
Yes, I do have antechamber in file at  "/home/saeed/miniconda3/envs/htmd1.21.0/bin/"
